import {
  LucideAlertCircle,
  LucideAlertOctagon,
  LucideAlertTriangle,
  LucideUndo,
  LucideWifiOff,
  LucideRedo,
  LucideCloudOff,
  LucideMousePointer,
  LucideCloudLightning,
  LucideCheckCircle,
  LucideWifi,
  LucideAlignCenterHorizontal,
  LucideAlignCenterVertical,
  LucideTableProperties,
  LucideTrash2,
  LucideAlignCenter,
  LucideArrowDown,
  LucideAlignEndHorizontal,
  LucideAlignEndVertical,
  LucideAlignHorizontalDistributeCenter,
  LucideAlignHorizontalJustifyStart,
  LucideAlignHorizontalSpaceAround,
  LucideAlignJustify,
  LucideMessageCircleDashed,
  LucideAlignLeft,
  LucideSettings,
  LucideSettings2,
  LucideAlignRight,
  LucidePencil,
  LucideAlignStartHorizontal,
  LucideAlignStartVertical,
  LucideAlignVerticalDistributeCenter,
  LucideAlignVerticalDistributeEnd,
  LucideAlignVerticalJustifyStart,
  LucideAlignVerticalSpaceAround,
  LucideArchiveX,
  LucideArchive,
  LucideAreaChart,
  LucideArrowDownCircle,
  LucideArrowDownUp,
  LucideArrowDownWideNarrow,
  LucideArrowLeftToLine,
  LucideArrowRightToLine,
  LucideArrowUpRightFromSquare,
  LucideAtSign,
  LucideBadgeCheck,
  LucideBan,
  LucideBellRing,
  LucideBlocks,
  LucideBookImage,
  LucideCheck,
  LucideChevronLeftCircle,
  LucideChevronRightCircle,
  LucideChevronLeft,
  LucideChevronRight,
  LucideChevronUp,
  LucideCircleEllipsis,
  LucideCircleUserRound,
  LucideClipboardPen,
  LucideClipboard,
  LucideCode2,
  LucideCode,
  LucideCog,
  LucideColumns4,
  LucideColumns3,
  LucideColumns2,
  LucideCombine,
  LucideCopyCheck,
  LucideCopyMinus,
  LucideCopyPlus,
  LucideCopyX,
  LucideCopy,
  LucideDatabaseBackup,
  LucideDatabase,
  LucideDelete,
  LucideDice1,
  LucideDice2,
  LucideDice3,
  LucideDice4,
  LucideDice5,
  LucideDice6,
  LucideDownloadCloud,
  LucideDownload,
  LucideEqual,
  LucideExpand,
  LucideExternalLink,
  LucideEyeOff,
  LucideEye,
  LucideFileCode2,
  LucideFileCode,
  LucideFilePen,
  LucideFilePlus2,
  LucideFileStack,
  LucideFiles,
  LucideFile,
  LucideFlag,
  LucideFlipVertical2,
  LucideFlipVertical,
  LucideFlipHorizontal,
  LucideFoldHorizontal,
  LucideGalleryHorizontal,
  LucideGalleryThumbnails,
  LucideGalleryVerticalEnd,
  LucideGalleryVertical,
  LucideGalleryHorizontalEnd,
  LucideGanttChart,
  LucideGrid2x2,
  LucideGrid3x3,
  LucideHeart,
  LucideHelpCircle,
  LucideHome,
  LucideInfo,
  LucideKeyRound,
  LucideLayers2,
  LucideLayers3,
  LucideLayers,
  LucideLayoutDashboard,
  LucideLayoutGrid,
  LucideLayoutList,
  LucideLayoutPanelLeft,
  LucideLayoutPanelTop,
  LucideLayoutTemplate,
  LucideListChecks,
  LucideLoader,
  LucideLoader2,
  LucideLockKeyhole,
  LucideLock,
  LucideList,
  LucideMessageSquareWarning,
  LucideMinimize,
  LucideMinimize2,
  LucideMinusCircle,
  LucideMoreHorizontal,
  LucideMoreVertical,
  LucideNetwork,
  LucidePanelsTopLeft,
  LucidePanelsRightBottom,
  LucidePlusCircle,
  LucidePlusSquare,
  LucidePlus,
  LucideSlidersHorizontal,
  LucidePalette,
  LucideToyBrick,
  LucideGroup,
  ArrowLeftFromLine,
  LucideDatabaseZap,
  LucideUnlockKeyhole,
  LucideHistory,
  LucideSearch,
  LucideGlobe,
  LucideAArrowDown,
  LucideAArrowUp,
  LucideALargeSmall,
  LucideAccessibility,
  LucideAlarmClock,
  LucideAlarmClockCheck,
  LucideAlignHorizontalDistributeEnd,
  LucideAlignHorizontalDistributeStart,
  LucideAlignHorizontalJustifyCenter,
  LucideAlignHorizontalJustifyEnd,
  LucideAlignHorizontalSpaceBetween,
  LucideAlignVerticalDistributeStart,
  LucideAlignVerticalJustifyCenter,
  LucideAlignVerticalJustifyEnd,
  LucideAlignVerticalSpaceBetween,
  LucideAmpersand,
  LucideAmpersands,
  LucideAnchor,
  LucideAngry,
  LucideAnnoyed,
  LucideAppWindow,
  LucideArchiveRestore,
  LucideArrowBigDown,
  LucideArrowBigDownDash,
  LucideArrowBigLeft,
  LucideArrowBigLeftDash,
  LucideArrowBigRight,
  LucideArrowBigRightDash,
  LucideArrowBigUp,
  LucideArrowBigUpDash,
  LucideArrowDown01,
  LucideArrowDown10,
  LucideArrowDownAZ,
  LucideArrowDownLeftFromCircle,
  LucideArrowDownNarrowWide,
  LucideArrowDownRightFromCircle,
  LucideArrowRightCircle,
  LucideArrowUpCircle,
  LucideArrowUpLeftFromCircle,
  LucideArrowUpRightFromCircle,
  LucideAsterisk,
  LucideAtom,
  LucideBadge,
  LucideBadgeAlert,
  LucideBadgeCent,
  LucideBadgeDollarSign,
  LucideBadgeEuro,
  LucideBadgeHelp,
  LucideBadgeIndianRupee,
  LucideBadgeInfo,
  LucideBadgeJapaneseYen,
  LucideBadgeMinus,
  LucideBadgePercent,
  LucideBadgePlus,
  LucideBadgePoundSterling,
  LucideBadgeRussianRuble,
  LucideBadgeSwissFranc,
  LucideBadgeX,
  LucideBarChart,
  LucideBarChart2,
  LucideBarChart3,
  LucideBarChart4,
  LucideBarChartBig,
  LucideBarChartHorizontal,
  LucideBarChartHorizontalBig,
  LucideBaseline,
  LucideBell,
  LucideBellDot,
  LucideBellOff,
  LucideBellPlus,
  LucideBetweenHorizontalEnd,
  LucideBetweenHorizontalStart,
  LucideBetweenVerticalEnd,
  LucideBetweenVerticalStart,
  LucideChevronDown,
  LucideChevronDownCircle,
  LucideChevronDownSquare,
  LucideChevronFirst,
  LucideChevronLast,
  LucideChevronLeftSquare,
  LucideChevronRightSquare,
  LucideChevronUpCircle,
  LucideChevronUpSquare,
  LucideChevronsDown,
  LucideChevronsDownUp,
  LucideChevronsLeft,
  LucideChevronsLeftRight,
  LucideChevronsRight,
  LucideChevronsRightLeft,
  LucideChevronsUp,
  LucideChevronsUpDown,
  LucideCodeSquare,
  LucideCodepen,
  LucideCodesandbox,
  LucideFoldVertical,
  LucideFolder,
  LucideFolderOpen,
  LucideFolderOutput,
  LucideFolderPen,
  LucideFolderPlus,
  LucideFolderRoot,
  LucideFolderSearch,
  LucideFolderSearch2,
  LucideFolderSymlink,
  LucideFolderSync,
  LucideFolderTree,
  LucideFolderUp,
  LucideFolderX,
  LucideFolders,
  LucideFootprints,
  LucideForklift,
  LucideFormInput,
  LucideFullscreen,
  LucideFunctionSquare,
  LucideGanttChartSquare,
  LucideGitBranch,
  LucideGitBranchPlus,
  LucideGitCommitHorizontal,
  LucideGitCommitVertical,
  LucideGitCompare,
  LucideGitCompareArrows,
  LucideGitFork,
  LucideGitGraph,
  LucideGitMerge,
  LucideGitPullRequest,
  LucideGitPullRequestArrow,
  LucideGitPullRequestClosed,
  LucideGitPullRequestCreate,
  LucideGitPullRequestCreateArrow,
  LucideGitPullRequestDraft,
  LucideGithub,
  LucideGitlab,
  LucideGlobe2,
  LucideHeading,
  LucideHeading1,
  LucideHeading2,
  LucideHeading3,
  LucideHeading4,
  LucideHeading5,
  LucideHeading6,
  LucideHighlighter,
  LucideImage,
  LucideImageDown,
  LucideImageMinus,
  LucideImageOff,
  LucideImagePlus,
  LucideImport,
  LucideInbox,
  LucideInstagram,
  LucideItalic,
  LucideKanbanSquare,
  LucideKey,
  LucideKeyboard,
  LucideLineChart,
  LucideLink,
  LucideLink2,
  LucideLink2Off,
  LucideLinkedin,
  LucideListCollapse,
  LucideListEnd,
  LucideListFilter,
  LucideListMinus,
  LucideListMusic,
  LucideListOrdered,
  LucideListPlus,
  LucideListRestart,
  LucideListStart,
  LucideListTodo,
  LucideListTree,
  LucideListVideo,
  LucideListX,
  LucideLogIn,
  LucideLogOut,
  LucideMailbox,
  LucideMaximize,
  LucideMaximize2,
  LucideMenu,
  LucideMenuSquare,
  LucideMerge,
  LucideMove,
  LucideMove3d,
  LucideMoveDiagonal,
  LucideMoveDiagonal2,
  LucideMoveDown,
  LucideMoveDownLeft,
  LucideMoveDownRight,
  LucideMoveHorizontal,
  LucideMoveLeft,
  LucideMoveRight,
  LucideMoveUp,
  LucideMoveUpLeft,
  LucideMoveUpRight,
  LucideMoveVertical,
  LucideNavigation,
  LucidePanelBottomClose,
  LucidePanelBottomOpen,
  LucidePanelLeftClose,
  LucidePanelLeftOpen,
  LucidePanelRightClose,
  LucidePanelRightOpen,
  LucidePanelTopClose,
  LucidePanelTopOpen,
  LucidePause,
  LucidePhone,
  LucidePi,
  LucidePiSquare,
  LucidePointer,
  LucidePointerOff,
  LucideQrCode,
  LucideRouter,
  LucideRows2,
  LucideRows3,
  LucideRows4,
  LucideSave,
  LucideSaveAll,
  LucideScale,
  LucideScale3d,
  LucideScaling,
  LucideScreenShare,
  LucideScreenShareOff,
  LucideScroll,
  LucideScrollText,
  LucideSearchCheck,
  LucideSearchCode,
  LucideSearchSlash,
  LucideSearchX,
  LucideSend,
  LucideSendToBack,
  LucideSeparatorHorizontal,
  LucideSeparatorVertical,
  LucideSkipBack,
  LucideSkipForward,
  LucideSkull,
  LucideSlack,
  LucideSlash,
  LucideSlashSquare,
  LucideSlice,
  LucideStepBack,
  LucideStepForward,
  LucideStrikethrough,
  LucideText,
  LucideTextCursor,
  LucideTextCursorInput,
  LucideTextQuote,
  LucideTextSearch,
  LucideTextSelect,
  LucideTriangle,
  LucideTriangleRight,
  LucideUnderline,
  LucideUndo2,
  LucideUndoDot,
  LucideUnfoldHorizontal,
  LucideUnfoldVertical,
  LucideUngroup,
  LucideUnlink,
  LucideUnlink2,
  LucideUnlock,
  LucideUser,
  LucideUserCheck,
  LucideUserCog,
  LucideUserMinus,
  LucideUserPlus,
  LucideUserRound,
  LucideUserRoundCheck,
  LucideUserRoundCog,
  LucideUserRoundMinus,
  LucideUserRoundPlus,
  LucideUserRoundSearch,
  LucideUserRoundX,
  LucideUserSearch,
  LucideUserX,
  LucideUsers,
  LucideUsersRound,
  LucideVote,
  LucideWebhook,
  LucideZoomIn,
  LucideZoomOut,
  LucideBold,
  LucideType,
  LucideCircle,
  LucideXCircle,
  LucideGripVertical,
  LucideClipboardCopy,
  LucideClipboardPaste,
  LucideDollarSign,
  LucideEuro,
  LucideMail,
  LucideCalendar,
  LucideFileText,
  LucideVideo,
  LucideStretchVertical,
  LucideStretchHorizontal,
  LucideX,
  LucideSquare,
  LucidePanelTop,
  LucidePanelLeft,
  LucidePanelBottom,
  LucideLightbulb,
  LucideHash,
  LucidePaintbrush,
  LucideToggleLeft,
  LucideCheckSquare2,
  LucideCalendarRange,
  LucideCalendarDays,
  LucideBraces,
  LucideScanBarcode,
  LucideWrapText,
  LucideTerminal,
  LucideTable2,
  LucideCircleUser,
  LucideGripHorizontal,
  LucideGrip,
  LucideSignalHigh,
  LucideSignalMedium,
  LucideSignalLow,
  LucideSignal,
  LucideSignalZero,
  LucideUpload,
  LucideFileUp,
  LucideSun,
  LucideMoon,
  LucideTvMinimal,
  LucideLaptopMinimal,
  LucideSunMoon,
  LucideEclipse,
  LucideSunDim,
  LucideSunMedium,
  LucideSunrise,
  LucideRainbow,
  LucideSunset,
} from "lucide-react";

export type LucideIconType = {
  component: React.ComponentType;
  tags: string[];
};

/**
 * Lucide Icon Map - A mapping of all Lucide icons to their respective components and tags
 * @returns LucideIconMap - A mapping of all Lucide icons to their respective components and tags
 * All icons can be seen here: https://lucide.dev/icons/
 *
 */
const lucideIconMap = {
  redo: {
    component: LucideRedo,
    tags: [
      "redo",
      "repeat",
      "refresh",
      "reload",
      "renew",
      "replay",
      "revert",
      "redo",
      "repeat",
      "refresh",
      "reload",
      "renew",
      "replay",
      "revert",
    ],
  },
  sun: {
    component: LucideSun,
    tags: [
      "sun",
      "brightness",
      "light",
      "weather",
      "solar",
      "energy",
      "power",
      "electricity",
      "energy",
      "electric",
      "charge",
      "electric charge",
    ],
  },
  "sun-moon": {
    component: LucideSunMoon,
    tags: ["sun", "moon", "brightness"],
  },
  eclipse: {
    component: LucideEclipse,
    tags: ["sun", "moon", "brightness"],
  },
  "sun-dim": {
    component: LucideSunDim,
    tags: ["sun", "brightness"],
  },
  "sun-medium": {
    component: LucideSunMedium,
    tags: ["sun", "brightness"],
  },
  sunrise: {
    component: LucideSunrise,
  },
  sunset: {
    component: LucideSunset,
  },
  rainbow: {
    component: LucideRainbow,
  },
  moon: {
    component: LucideMoon,
  },
  "tv-minimal": {
    component: LucideTvMinimal,
    tags: [
      "tv",
      "television",
      "display",
      "screen",
      "monitor",
      "device",
      "technology",
      "electronic",
      "gadget",
    ],
  },
  "laptop-minimal": {
    component: LucideLaptopMinimal,
    tags: [
      "laptop",
      "computer",
      "device",
      "technology",
      "electronic",
      "gadget",
    ],
  },
  "cloud-off": {
    component: LucideCloudOff,
    tags: ["Cloud", "connection", "internet", "connected"],
  },
  "circle-plus": {
    component: LucidePlusCircle,
    tags: [
      "add",
      "create",
      "new",
      "plus",
      "circle",
      "add",
      "create",
      "new",
      "plus",
      "circle",
    ],
  },
  "square-plus": {
    component: LucidePlusSquare,
    tags: [
      "add",
      "create",
      "new",
      "plus",
      "square",
      "add",
      "create",
      "new",
      "plus",
      "square",
    ],
  },
  "folder-plus": {
    component: LucideFolderPlus,
    tags: [
      "add",
      "create",
      "new",
      "plus",
      "folder",
      "add",
      "create",
      "new",
      "plus",
      "folder",
    ],
  },
  "signal-high": {
    component: LucideSignalHigh,
    tags: ["signal", "connection", "internet"],
  },
  "signal-medium": {
    component: LucideSignalMedium,
    tags: ["signal", "connection", "internet"],
  },
  "signal-low": {
    component: LucideSignalLow,
    tags: ["signal", "connection", "internet"],
  },
  "signal-zero": {
    component: LucideSignalZero,
    tags: ["signal", "connection", "internet"],
  },
  "circle-x": {
    component: LucideXCircle,
    tags: [
      "circle",
      "x",
      "close",
      "remove",
      "delete",
      "cancel",
      "clear",
      "close",
      "remove",
      "delete",
      "cancel",
      "clear",
    ],
  },
  signal: {
    component: LucideSignal,
    tags: ["signal", "connection", "internet"],
  },
  wifi: {
    component: LucideWifi,
    tags: ["wifi", "connection", "internet"],
  },
  "wifi-off": {
    component: LucideWifiOff,
    tags: ["wifi", "connection", "internet"],
  },
  "table-2": {
    component: LucideTable2,
    tags: [
      "table",
      "data",
      "spreadsheet",
      "grid",
      "table",
      "data",
      "spreadsheet",
      "grid",
    ],
  },
  "table-properties": {
    component: LucideTableProperties,
    tags: [
      "table",
      "data",
      "spreadsheet",
      "grid",
      "table",
      "data",
      "spreadsheet",
      "grid",
    ],
  },
  "cloud-lightning": {
    component: LucideCloudLightning,
    tags: [
      "cloud",
      "lightning",
      "storm",
      "thunder",
      "weather",
      "rain",
      "electricity",
      "power",
      "energy",
      "electric",
      "charge",
      "electric charge",
      "electricity",
      "power",
      "energy",
      "electric",
      "charge",
      "electric charge",
    ],
  },
  "scan-barcode": {
    component: LucideScanBarcode,
    tags: [
      "scan",
      "barcode",
      "code",
      "reader",
      "scanner",
      "read",
      "scan",
      "barcode",
      "code",
      "reader",
      "scanner",
      "read",
    ],
  },
  braces: {
    component: LucideBraces,
    tags: [
      "braces",
      "curly braces",
      "brackets",
      "curly brackets",
      "parentheses",
      "round brackets",
      "square brackets",
    ],
  },
  "square-check": {
    component: LucideCheckSquare2,
    tags: [
      "check",
      "mark",
      "tick",
      "approve",
      "confirm",
      "success",
      "done",
      "completed",
      "finished",
      "checkmark",
    ],
  },
  "calendar-range": {
    component: LucideCalendarRange,
    tags: [
      "calendar",
      "date",
      "time",
      "schedule",
      "event",
      "appointment",
      "meeting",
      "reminder",
      "deadline",
    ],
  },
  "circle-chevron-up": {
    component: LucideChevronUpCircle,
    tags: [
      "chevron",
      "arrow",
      "up",
      "circle",
      "chevron",
      "arrow",
      "up",
      "circle",
    ],
  },
  "circle-chevron-down": {
    component: LucideChevronDownCircle,
    tags: [
      "chevron",
      "arrow",
      "down",
      "circle",
      "chevron",
      "arrow",
      "down",
      "circle",
    ],
  },
  "circle-chevron-left": {
    component: LucideChevronLeftCircle,
    tags: [
      "chevron",
      "arrow",
      "left",
      "circle",
      "chevron",
      "arrow",
      "left",
      "circle",
    ],
  },
  "circle-chevron-right": {
    component: LucideChevronRightCircle,
    tags: [
      "chevron",
      "arrow",
      "right",
      "circle",
      "chevron",
      "arrow",
      "right",
      "circle",
    ],
  },
  "circle-user": {
    component: LucideCircleUser,
    tags: [
      "user",
      "avatar",
      "profile",
      "account",
      "person",
      "circle",
      "user",
      "avatar",
      "profile",
      "account",
      "person",
    ],
  },

  "circle-check-circle": {
    component: LucideCheckCircle,
    tags: [
      "check",
      "mark",
      "tick",
      "approve",
      "confirm",
      "success",
      "done",
      "completed",
      "finished",
      "checkmark",
    ],
  },
  "circle-user-round": {
    component: LucideCircleUserRound,
    tags: [
      "user",
      "avatar",
      "profile",
      "account",
      "person",
      "circle",
      "user",
      "avatar",
      "profile",
      "account",
      "person",
    ],
  },
  "calendar-days": {
    component: LucideCalendarDays,
    tags: [
      "calendar",
      "date",
      "time",
      "schedule",
      "event",
      "appointment",
      "meeting",
      "reminder",
      "deadline",
    ],
  },
  terminal: {
    component: LucideTerminal,
    tags: [
      "terminal",
      "code",
      "command",
      "prompt",
      "shell",
      "console",
      "terminal",
      "code",
      "command",
      "prompt",
      "shell",
      "console",
    ],
  },
  "toggle-left": {
    component: LucideToggleLeft,
    tags: [
      "toggle",
      "switch",
      "on",
      "off",
      "enable",
      "disable",
      "activate",
      "deactivate",
      "toggle",
      "switch",
      "on",
      "off",
      "enable",
      "disable",
      "activate",
      "deactivate",
    ],
  },
  "wrap-text": {
    component: LucideWrapText,
    tags: ["wrap", "text", "wrap", "text"],
  },
  paintbrush: {
    component: LucidePaintbrush,
    tags: [
      "paint",
      "brush",
      "draw",
      "sketch",
      "color",
      "paintbrush",
      "paint",
      "brush",
      "draw",
      "sketch",
      "color",
    ],
  },
  "square-mouse-pointer": {
    component: LucideMousePointer,
    tags: [],
  },
  "mouse-pointer-click": {
    component: LucideMousePointer,
    tags: [],
  },
  "stretch-vertical": {
    component: LucideStretchVertical,
    tags: [],
  },
  "stretch-horizontal": {
    component: LucideStretchHorizontal,
    tags: [],
  },
  "panel-top": {
    component: LucidePanelTop,
    tags: ["navbar", "panel", "top"],
  },
  "panel-left": {
    component: LucidePanelLeft,
    tags: ["navbar", "panel", "left"],
  },
  "panel-bottom": {
    component: LucidePanelBottom,
    tags: ["navbar", "panel", "bottom"],
  },
  "trash-2": {
    component: LucideTrash2,
    tags: [
      "delete",
      "remove",
      "trash",
      "bin",
      "garbage",
      "waste",
      "discard",
      "junk",
      "rubbish",
    ],
  },
  square: {
    component: LucideSquare,
    tags: [
      "shape",
      "geometry",
      "col",
      "column",
      "square",
      "rectangle",
      "box",
      "cube",
      "block",
      "brick",
      "tile",
    ],
  },
  ellipsis: {
    component: LucideMoreHorizontal,
    tags: [
      "more",
      "ellipsis",
      "menu",
      "options",
      "settings",
      "dots",
      "kebab",
      "overflow",
      "more",
      "ellipsis",
      "menu",
      "options",
      "settings",
      "dots",
      "kebab",
      "overflow",
    ],
  },
  mail: {
    component: LucideMail,
    tags: [
      "email",
      "message",
      "letter",
      "post",
      "send",
      "inbox",
      "outbox",
      "compose",
      "draft",
      "spam",
      "trash",
      "archive",
      "folder",
    ],
  },
  settings: {
    component: LucideSettings,
    tags: [
      "settings",
      "options",
      "preferences",
      "configuration",
      "controls",
      "tools",
      "gear",
      "cog",
      "settings",
      "options",
      "preferences",
      "configuration",
      "controls",
      "tools",
      "gear",
      "cog",
    ],
  },
  "clipboard-paste": {
    component: LucideClipboardPaste,
    tags: [
      "clipboard",
      "paste",
      "copy",
      "cut",
      "document",
      "file",
      "data",
      "information",
      "record",
      "storage",
      "archive",
    ],
  },
  hash: {
    component: LucideHash,
    tags: [
      "hash",
      "number",
      "code",
      "programming",
      "development",
      "script",
      "syntax",
      "markup",
      "code",
      "programming",
      "development",
      "script",
      "syntax",
      "markup",
    ],
  },

  "clipboard-copy": {
    component: LucideClipboardCopy,
    tags: [
      "clipboard",
      "copy",
      "paste",
      "cut",
      "document",
      "file",
      "data",
      "information",
      "record",
      "storage",
      "archive",
    ],
  },
  lightbulb: {
    component: LucideLightbulb,
    tags: [
      "light",
      "bulb",
      "lamp",
      "lightbulb",
      "light",
      "bulb",
      "lamp",
      "lightbulb",
    ],
  },
  "ellipsis-vertical": {
    component: LucideMoreVertical,
    tags: [
      "more",
      "ellipsis",
      "menu",
      "options",
      "settings",
      "dots",
      "kebab",
      "overflow",
      "more",
      "ellipsis",
      "menu",
      "options",
      "settings",
      "dots",
      "kebab",
      "overflow",
    ],
  },
  "ellipsis-horizontal": {
    component: LucideMoreHorizontal,
    tags: [
      "more",
      "ellipsis",
      "menu",
      "options",
      "settings",
      "dots",
      "kebab",
      "overflow",
      "more",
      "ellipsis",
      "menu",
      "options",
      "settings",
      "dots",
      "kebab",
      "overflow",
    ],
  },
  "settings-2": {
    component: LucideSettings2,
    tags: [
      "settings",
      "options",
      "preferences",
      "configuration",
      "controls",
      "tools",
      "gear",
      "cog",
      "settings",
      "options",
      "preferences",
      "configuration",
      "controls",
      "tools",
      "gear",
      "cog",
    ],
  },
  circle: {
    component: LucideCircle,
    tags: ["round", "shape", "geometry", "circular", "oval", "ellipse"],
  },
  "arrow-down-up": {
    component: LucideArrowDownUp,
    tags: [],
  },
  "arrow-down-wide-narrow": {
    component: LucideArrowDownWideNarrow,
    tags: [],
  },
  video: {
    component: LucideVideo,
    tags: [],
  },
  "arrow-left-to-line": {
    component: LucideArrowLeftToLine,
    tags: [],
  },
  "file-text": {
    component: LucideFileText,
    tags: [],
  },
  "arrow-right-to-line": {
    component: LucideArrowRightToLine,

    tags: [],
  },
  "x-circle": {
    component: LucideXCircle,
    tags: [],
  },
  "arrow-up-right-from-square": {
    component: LucideArrowUpRightFromSquare,

    tags: [],
  },

  blocks: {
    component: LucideBlocks,

    tags: [],
  },
  "book-image": {
    component: LucideBookImage,

    tags: [],
  },
  check: {
    component: LucideCheck,

    tags: [],
  },

  "circle-ellipsis": {
    component: LucideCircleEllipsis,

    tags: [],
  },

  "message-circle-dashed": {
    component: LucideMessageCircleDashed,
    tags: [],
  },
  "dollar-sign": {
    component: LucideDollarSign,
    tags: [
      "currency",
      "money",
      "cash",
      "finance",
      "economy",
      "bank",
      "banking",
      "investment",
      "savings",
      "wealth",
      "credit",
      "debit",
      "loan",
      "mortgage",
      "interest",
      "exchange",
      "rate",
      "currency exchange",
      "currency converter",
      "currency rate",
      "currency converter",
      "currency rate",
    ],
  },
  eur: {
    component: LucideEuro,
    tags: [
      "currency",
      "money",
      "cash",
      "finance",
      "economy",
      "bank",
      "banking",
      "investment",
      "savings",
      "wealth",
      "credit",
      "debit",
      "loan",
      "mortgage",
      "interest",
      "exchange",
      "rate",
      "currency exchange",
      "currency converter",
      "currency rate",
      "currency converter",
      "currency rate",
    ],
  },
  "indian-rupee": {
    component: LucideBadgeIndianRupee,
    tags: [
      "currency",
      "money",
      "cash",
      "finance",
      "economy",
      "bank",
      "banking",
      "investment",
      "savings",
      "wealth",
      "credit",
      "debit",
      "loan",
      "mortgage",
      "interest",
      "exchange",
      "rate",
      "currency exchange",
      "currency converter",
      "currency rate",
      "currency converter",
      "currency rate",
    ],
  },
  "japanese-yen": {
    component: LucideBadgeJapaneseYen,
    tags: [
      "currency",
      "money",
      "cash",
      "finance",
      "economy",
      "bank",
      "banking",
      "investment",
      "savings",
      "wealth",
      "credit",
      "debit",
      "loan",
      "mortgage",
      "interest",
      "exchange",
      "rate",
      "currency exchange",
      "currency converter",
      "currency rate",
      "currency converter",
      "currency rate",
    ],
  },
  "pound-sterling": {
    component: LucideBadgePoundSterling,
    tags: [
      "currency",
      "money",
      "cash",
      "finance",
      "economy",
      "bank",
      "banking",
      "investment",
      "savings",
      "wealth",
      "credit",
      "debit",
      "loan",
      "mortgage",
      "interest",
      "exchange",
      "rate",
      "currency exchange",
      "currency converter",
      "currency rate",
      "currency converter",
      "currency rate",
    ],
  },
  "clipboard-pen": {
    component: LucideClipboardPen,
    tags: [],
  },
  "swiss-franc": {
    component: LucideBadgeSwissFranc,
    tags: [
      "currency",
      "money",
      "cash",
      "finance",
      "economy",
      "bank",
      "banking",
      "investment",
      "savings",
      "wealth",
      "credit",
      "debit",
      "loan",
      "mortgage",
      "interest",
      "exchange",
      "rate",
      "currency exchange",
      "currency converter",
      "currency rate",
      "currency converter",
      "currency rate",
    ],
  },
  "russian-ruble": {
    component: LucideBadgeRussianRuble,
    tags: [
      "currency",
      "money",
      "cash",
      "finance",
      "economy",
      "bank",
      "banking",
      "investment",
      "savings",
      "wealth",
      "credit",
      "debit",
      "loan",
      "mortgage",
      "interest",
      "exchange",
      "rate",
      "currency exchange",
      "currency converter",
      "currency rate",
      "currency converter",
      "currency rate",
    ],
  },
  clipboard: {
    component: LucideClipboard,
    tags: [
      " clipboard",
      "copy",
      "paste",
      "cut",
      "document",
      "file",
      "data",
      "information",
      "record",
      "storage",
      "archive",
    ],
  },
  pencil: {
    component: LucidePencil,
    tags: [
      "edit",
      "write",
      "draw",
      "sketch",
      "note",
      "notebook",
      "paper",
      "document",
      "file",
      "data",
      "information",
      "record",
      "storage",
      "archive",
    ],
  },
  "columns-4": {
    component: LucideColumns4,
    tags: [
      "layout",
      "arrange",
      "arrangement",
      "order",
      "col",
      "column",
      "columns",
    ],
  },
  "columns-3": {
    component: LucideColumns3,
    tags: [
      "layout",
      "arrange",
      "arrangement",
      "order",
      "col",
      "column",
      "columns",
    ],
  },
  "columns-2": {
    component: LucideColumns2,
    tags: [
      "layout",
      "arrange",
      "arrangement",
      "order",
      "col",
      "column",
      "columns",
    ],
  },
  combine: {
    component: LucideCombine,
    tags: [
      "merge",
      "join",
      "combine",
      "unite",
      "mix",
      "blend",
      "fuse",
      "merge",
      "join",
      "combine",
      "unite",
      "mix",
      "blend",
      "fuse",
    ],
  },
  "grip-vertical": {
    component: LucideGripVertical,
    tags: [
      "drag",
      "move",
      "resize",
      "handle",
      "grip",
      "grab",
      "hold",
      "control",
      "adjust",
      "manipulate",
      "grip",
      "drag",
      "move",
      "resize",
      "handle",
      "grip",
      "grab",
      "hold",
      "control",
      "adjust",
      "manipulate",
    ],
  },
  "grip-horizontal": {
    component: LucideGripHorizontal,
    tags: [
      "drag",
      "move",
      "resize",
      "handle",
      "grip",
      "grab",
      "hold",
      "control",
      "adjust",
    ],
  },
  grip: {
    component: LucideGrip,
    tags: [
      "drag",
      "move",
      "resize",
      "handle",
      "grip",
      "grab",
      "hold",
      "control",
      "adjust",
    ],
  },
  "copy-check": {
    component: LucideCopyCheck,

    tags: [
      "copy",
      "duplicate",
      "clone",
      "replicate",
      "check",
      "verify",
      "confirm",
      "approve",
      "copy",
      "duplicate",
      "clone",
      "replicate",
      "check",
      "verify",
      "confirm",
      "approve",
    ],
  },
  "copy-minus": {
    component: LucideCopyMinus,

    tags: [],
  },
  "copy-plus": {
    component: LucideCopyPlus,

    tags: [],
  },
  "copy-x": {
    component: LucideCopyX,

    tags: [],
  },
  copy: {
    component: LucideCopy,

    tags: [],
  },
  "database-backup": {
    component: LucideDatabaseBackup,

    tags: [],
  },
  database: {
    component: LucideDatabase,

    tags: [],
  },
  delete: {
    component: LucideDelete,

    tags: [],
  },
  "dice-1": {
    component: LucideDice1,

    tags: [],
  },
  "dice-2": {
    component: LucideDice2,

    tags: [],
  },
  "dice-3": {
    component: LucideDice3,

    tags: [],
  },
  "dice-4": {
    component: LucideDice4,

    tags: [],
  },
  "dice-5": {
    component: LucideDice5,

    tags: [],
  },
  "dice-6": {
    component: LucideDice6,

    tags: [],
  },
  "download-cloud": {
    component: LucideDownloadCloud,

    tags: [],
  },
  download: {
    component: LucideDownload,

    tags: [],
  },
  equal: {
    component: LucideEqual,

    tags: [],
  },
  expand: {
    component: LucideExpand,

    tags: [],
  },
  "external-link": {
    component: LucideExternalLink,

    tags: [],
  },
  "eye-off": {
    component: LucideEyeOff,

    tags: [],
  },
  eye: {
    component: LucideEye,

    tags: [],
  },
  "file-code-2": {
    component: LucideFileCode2,

    tags: [],
  },
  "file-code": {
    component: LucideFileCode,

    tags: [],
  },
  "file-pen": {
    component: LucideFilePen,

    tags: [],
  },
  "file-plus-2": {
    component: LucideFilePlus2,

    tags: [],
  },
  "file-stack": {
    component: LucideFileStack,

    tags: [],
  },
  files: {
    component: LucideFiles,

    tags: [
      "files",
      "documents",
      "data",
      "information",
      "records",
      "storage",
      "archive",
      "file",
    ],
  },
  file: {
    component: LucideFile,

    tags: [
      "file",
      "document",
      "data",
      "information",
      "record",
      "storage",
      "archive",
    ],
  },
  flag: {
    component: LucideFlag,

    tags: [
      "flag",
      "country",
      "notification",
      "national",
      "patriotic",
      "patriotism",
    ],
  },
  "flip-vertical-2": {
    component: LucideFlipVertical2,

    tags: ["flip", "rotate", "mirror", "invert", "reverse"],
  },
  "flip-vertical": {
    component: LucideFlipVertical,

    tags: ["flip", "rotate", "mirror", "invert", "reverse"],
  },
  "flip-horizontal": {
    component: LucideFlipHorizontal,

    tags: ["flip", "rotate", "mirror", "invert", "reverse"],
  },
  "fold-horizontal": {
    component: LucideFoldHorizontal,

    tags: ["fold", "horizontal", "collapse", "hide", "reduce", "shrink"],
  },

  "grid-2x2": {
    component: LucideGrid2x2,

    tags: ["grid", "layout", "arrange", "arrangement", "order"],
  },
  "grid-3x3": {
    component: LucideGrid3x3,

    tags: ["grid", "layout", "arrange", "arrangement", "order"],
  },
  heart: {
    component: LucideHeart,

    tags: [
      "love",
      "like",
      "favorite",
      "emotion",
      "feeling",
      "care",
      "affection",
      "passion",
      "romance",
      "valentine",
      "valentines",
      "valentines day",
      "heart",
    ],
  },
  "help-circle": {
    component: LucideHelpCircle,

    tags: [
      "help",
      "question",
      "support",
      "faq",
      "info",
      "information",
      "hint",
      "help",
    ],
  },
  home: {
    component: LucideHome,

    tags: [
      "home",
      "house",
      "homepage",
      "building",
      "residence",
      "dwelling",
      "habitat",
      "shelter",
      "accommodation",
      "home sweet home",
      "home sweet home",
    ],
  },

  "key-round": {
    component: LucideKeyRound,

    tags: ["key", "security"],
  },
  "layers-2": {
    component: LucideLayers2,

    tags: [],
  },
  "layers-3": {
    component: LucideLayers3,

    tags: [
      "layers",
      "stack",
      "stacked",
      "group",
      "grouped",
      "arrange",
      "arrangement",
      "order",
      "stacking",
      "stacked",
    ],
  },
  layers: {
    component: LucideLayers,

    tags: [
      "layers",
      "stack",
      "stacked",
      "group",
      "grouped",
      "arrange",
      "arrangement",
      "order",
      "stacking",
      "stacked",
    ],
  },
  "layout-dashboard": {
    component: LucideLayoutDashboard,

    tags: ["layout", "dashboard"],
  },
  "layout-grid": {
    component: LucideLayoutGrid,

    tags: ["layout", "grid"],
  },
  "layout-list": {
    component: LucideLayoutList,

    tags: ["layout", "list"],
  },
  "layout-panel-left": {
    component: LucideLayoutPanelLeft,
    tags: ["panels", "layout", "left"],
  },
  "layout-panel-top": {
    component: LucideLayoutPanelTop,
    tags: ["panels", "layout", "top"],
  },
  "layout-template": {
    component: LucideLayoutTemplate,
    tags: ["layout", "template"],
  },
  "lock-keyhole": {
    component: LucideLockKeyhole,
    tags: ["lock", "keyhole", "key", "security"],
  },
  lock: {
    component: LucideLock,
    tags: ["lock", "security"],
  },
  "message-square-warning": {
    component: LucideMessageSquareWarning,
    tags: ["message", "warning"],
  },
  minimize: {
    component: LucideMinimize,
    tags: ["minimize", "reduce", "shrink", "collapse", "hide"],
  },
  "minimize-2": {
    component: LucideMinimize2,
    tags: ["minimize", "reduce", "shrink", "collapse", "hide"],
  },
  "minus-circle": {
    component: LucideMinusCircle,
    tags: [
      "remove",
      "delete",
      "subtract",
      "negative",
      "minus",
      "cancel",
      "close",
    ],
  },
  "more-horizontal": {
    component: LucideMoreHorizontal,
    tags: [
      "more",
      "menu",
      "options",
      "settings",
      "dots",
      "kebab",
      "overflow",
      "ellipsis",
    ],
  },
  "more-vertical": {
    component: LucideMoreVertical,
    tags: [],
  },
  "panels-top-left": {
    component: LucidePanelsTopLeft,
    tags: ["panels", "layout", "top", "left"],
  },
  "panels-right-bottom": {
    component: LucidePanelsRightBottom,
    tags: ["panels", "layout", "right", "bottom"],
  },

  "sliders-horizontal": {
    component: LucideSlidersHorizontal,

    tags: ["sliders", "horizontal", "adjust", "control", "settings", "options"],
  },
  calendar: {
    component: LucideCalendar,
    tags: [
      "date",
      "time",
      "schedule",
      "event",
      "appointment",
      "meeting",
      "day",
      "month",
      "year",
      "week",
      "time",
      "clock",
      "reminder",
      "plan",
      "agenda",
      "diary",
      "journal",
      "organize",
      "schedule",
    ],
  },
  palette: {
    component: LucidePalette,

    tags: [],
  },
  "toy-brick": {
    component: LucideToyBrick,

    tags: [],
  },

  group: {
    component: LucideGroup,
    tags: [],
  },
  "arrow-left-from-line": {
    component: ArrowLeftFromLine,
    tags: [],
  },
  "database-zap": {
    component: LucideDatabaseZap,
    tags: [],
  },
  "unlock-keyhole": {
    component: LucideUnlockKeyhole,
    tags: [],
  },

  "a-arrow-down": {
    component: LucideAArrowDown,
    tags: ["letter", "font size", "text", "formatting", "smaller"],
  },
  "a-arrow-up": {
    component: LucideAArrowUp,
    tags: ["letter", "font size", "text", "formatting", "larger", "bigger"],
  },
  "a-large-small": {
    component: LucideALargeSmall,
    tags: ["letter", "font size", "text", "formatting"],
  },
  accessibility: {
    component: LucideAccessibility,
    tags: ["disability", "disabled", "dda", "wheelchair"],
  },
  "alarm-clock-check": {
    component: LucideAlarmClockCheck,
    tags: ["done", "todo", "tick", "complete", "task"],
  },
  "alarm-clock": { component: LucideAlarmClock, tags: ["morning"] },
  "alert-circle": {
    component: LucideAlertCircle,
    tags: ["warning", "alert", "danger", "exclamation mark"],
  },
  "alert-octagon": {
    component: LucideAlertOctagon,
    tags: ["warning", "alert", "danger", "exclamation mark"],
  },
  "alert-triangle": {
    component: LucideAlertTriangle,
    tags: ["warning", "alert", "danger", "exclamation mark", "linter"],
  },
  "align-center-horizontal": {
    component: LucideAlignCenterHorizontal,
    tags: ["items", "flex", "justify"],
  },
  "align-center-vertical": {
    component: LucideAlignCenterVertical,
    tags: ["items", "flex", "justify"],
  },
  "align-center": {
    component: LucideAlignCenter,
    tags: ["text", "alignment", "center"],
  },
  "align-end-horizontal": {
    component: LucideAlignEndHorizontal,
    tags: ["items", "bottom", "flex", "justify"],
  },
  "align-end-vertical": {
    component: LucideAlignEndVertical,
    tags: ["items", "right", "flex", "justify"],
  },
  "align-horizontal-distribute-center": {
    component: LucideAlignHorizontalDistributeCenter,
    tags: ["items", "flex", "justify", "space", "evenly", "around"],
  },
  "align-horizontal-distribute-end": {
    component: LucideAlignHorizontalDistributeEnd,
    tags: ["right", "items", "flex", "justify"],
  },
  "align-horizontal-distribute-start": {
    component: LucideAlignHorizontalDistributeStart,
    tags: ["left", "items", "flex", "justify"],
  },
  "align-horizontal-justify-center": {
    component: LucideAlignHorizontalJustifyCenter,
    tags: ["center", "items", "flex", "justify"],
  },
  "align-horizontal-justify-end": {
    component: LucideAlignHorizontalJustifyEnd,
    tags: ["right", "items", "flex", "justify"],
  },
  "align-horizontal-justify-start": {
    component: LucideAlignHorizontalJustifyStart,
    tags: ["left", "items", "flex", "justify"],
  },
  "align-horizontal-space-around": {
    component: LucideAlignHorizontalSpaceAround,
    tags: ["center", "items", "flex", "justify", "distribute", "between"],
  },
  "align-horizontal-space-between": {
    component: LucideAlignHorizontalSpaceBetween,
    tags: ["around", "items", "bottom", "flex", "justify"],
  },
  list: {
    component: LucideList,
    tags: ["menu", "items", "order", "unordered", "bullets"],
  },
  "align-justify": {
    component: LucideAlignJustify,
    tags: ["text", "alignment", "justified", "menu", "list"],
  },
  "align-left": {
    component: LucideAlignLeft,
    tags: ["text", "alignment", "left", "list"],
  },
  "align-right": {
    component: LucideAlignRight,
    tags: ["text", "alignment", "right"],
  },
  "align-start-horizontal": {
    component: LucideAlignStartHorizontal,
    tags: ["top", "items", "flex", "justify"],
  },
  "align-start-vertical": {
    component: LucideAlignStartVertical,
    tags: ["left", "items", "flex", "justify"],
  },
  "align-vertical-distribute-center": {
    component: LucideAlignVerticalDistributeCenter,
    tags: ["items", "flex", "justify", "space", "evenly", "around"],
  },
  "align-vertical-distribute-end": {
    component: LucideAlignVerticalDistributeEnd,
    tags: ["bottom", "items", "flex", "justify"],
  },
  "align-vertical-distribute-start": {
    component: LucideAlignVerticalDistributeStart,
    tags: ["top", "items", "flex", "justify"],
  },
  "align-vertical-justify-center": {
    component: LucideAlignVerticalJustifyCenter,
    tags: ["center", "items", "flex", "justify", "distribute", "between"],
  },
  "align-vertical-justify-end": {
    component: LucideAlignVerticalJustifyEnd,
    tags: ["bottom", "items", "flex", "justify", "distribute", "between"],
  },
  "align-vertical-justify-start": {
    component: LucideAlignVerticalJustifyStart,
    tags: ["top", "items", "flex", "justify", "distribute", "between"],
  },
  "align-vertical-space-around": {
    component: LucideAlignVerticalSpaceAround,
    tags: ["center", "items", "flex", "justify", "distribute", "between"],
  },
  "align-vertical-space-between": {
    component: LucideAlignVerticalSpaceBetween,
    tags: ["center", "items", "flex", "justify", "distribute", "between"],
  },

  ampersand: {
    component: LucideAmpersand,
    tags: ["and", "typography", "operator", "join", "concatenate", "code", "&"],
  },
  ampersands: {
    component: LucideAmpersands,
    tags: ["and", "operator", "then", "code", "&&"],
  },
  anchor: { component: LucideAnchor, tags: ["ship"] },
  angry: {
    component: LucideAngry,
    tags: ["emoji", "anger", "face", "emotion"],
  },
  annoyed: {
    component: LucideAnnoyed,
    tags: ["emoji", "nuisance", "face", "emotion"],
  },
  "app-window": {
    component: LucideAppWindow,
    tags: ["application", "executable"],
  },
  "archive-restore": {
    component: LucideArchiveRestore,
    tags: ["unarchive", "index", "backup", "box", "storage", "records"],
  },
  "archive-x": {
    component: LucideArchiveX,
    tags: ["index", "backup", "box", "storage", "records", "junk"],
  },
  archive: {
    component: LucideArchive,
    tags: ["index", "backup", "box", "storage", "records"],
  },
  "area-chart": {
    component: LucideAreaChart,
    tags: ["statistics", "diagram", "graph", "area"],
  },
  "arrow-big-down-dash": {
    component: LucideArrowBigDownDash,
    tags: ["backwards", "reverse", "slow", "direction", "south", "download"],
  },
  "arrow-big-down": {
    component: LucideArrowBigDown,
    tags: ["backwards", "reverse", "direction", "south"],
  },
  "arrow-big-left-dash": {
    component: LucideArrowBigLeftDash,
    tags: ["previous", "back", "direction", "west", "turn", "corner"],
  },
  "arrow-big-left": {
    component: LucideArrowBigLeft,
    tags: ["previous", "back", "direction", "west", "indicate turn"],
  },
  "arrow-big-right-dash": {
    component: LucideArrowBigRightDash,
    tags: ["next", "forward", "direction", "east", "turn", "corner"],
  },
  "arrow-big-right": {
    component: LucideArrowBigRight,
    tags: ["next", "forward", "direction", "east", "indicate turn"],
  },
  "arrow-big-up-dash": {
    component: LucideArrowBigUpDash,
    tags: [
      "caps lock",
      "capitals",
      "keyboard",
      "button",
      "mac",
      "forward",
      "direction",
      "north",
      "faster",
      "speed",
      "boost",
    ],
  },
  "arrow-big-up": {
    component: LucideArrowBigUp,
    tags: [
      "shift",
      "keyboard",
      "button",
      "mac",
      "capitalize",
      "capitalise",
      "forward",
      "direction",
      "north",
    ],
  },
  "arrow-down": {
    component: LucideArrowDown,
    tags: ["arrow", "arrrow down"],
  },
  "arrow-down-0-1": {
    component: LucideArrowDown01,
    tags: ["filter", "sort", "ascending", "numerical"],
  },
  "arrow-down-1-0": {
    component: LucideArrowDown10,
    tags: ["filter", "sort", "descending", "numerical"],
  },
  "arrow-down-a-z": {
    component: LucideArrowDownAZ,
    tags: ["filter", "sort", "ascending", "alphabetical"],
  },
  "arrow-down-circle": {
    component: LucideArrowDownCircle,
    tags: ["backwards", "reverse", "direction", "south", "sign", "button"],
  },
  "arrow-down-left-from-circle": {
    component: LucideArrowDownLeftFromCircle,
    tags: ["outwards", "direction", "south-west", "diagonal"],
  },
  "arrow-down-narrow-wide": {
    component: LucideArrowDownNarrowWide,
    tags: ["filter", "sort", "ascending"],
  },
  "arrow-down-right-from-circle": {
    component: LucideArrowDownRightFromCircle,
    tags: ["outwards", "direction", "south-east", "diagonal"],
  },
  "arrow-right-circle": {
    component: LucideArrowRightCircle,
    tags: [
      "next",
      "forward",
      "direction",
      "east",
      "sign",
      "turn",
      "button",
      "->",
    ],
  },
  "arrow-up-circle": {
    component: LucideArrowUpCircle,
    tags: ["forward", "direction", "north", "sign", "button"],
  },
  "arrow-up-left-from-circle": {
    component: LucideArrowUpLeftFromCircle,
    tags: [
      "outwards",
      "direction",
      "north-west",
      "diagonal",
      "keyboard",
      "button",
      "escape",
    ],
  },
  "arrow-up-right-from-circle": {
    component: LucideArrowUpRightFromCircle,
    tags: ["outwards", "direction", "north-east", "diagonal"],
  },
  asterisk: {
    component: LucideAsterisk,
    tags: [
      "reference",
      "times",
      "multiply",
      "multiplication",
      "operator",
      "code",
      "glob pattern",
      "wildcard",
      "*",
    ],
  },
  "at-sign": {
    component: LucideAtSign,
    tags: ["mention", "at", "email", "message", "@"],
  },
  atom: {
    component: LucideAtom,
    tags: [
      "atomic",
      "nuclear",
      "physics",
      "particle",
      "element",
      "molecule",
      "electricity",
      "energy",
      "chemistry",
    ],
  },
  "badge-alert": {
    component: LucideBadgeAlert,
    tags: ["check", "verified", "unverified", "security", "safety", "issue"],
  },
  "badge-cent": {
    component: LucideBadgeCent,
    tags: [
      "discount",
      "offer",
      "sale",
      "voucher",
      "tag",
      "monetization",
      "marketing",
      "finance",
      "financial",
      "exchange",
      "transaction",
      "payment",
      "cents",
      "dollar",
      "usd",
      "$",
      "¢",
    ],
  },
  "badge-check": { component: LucideBadgeCheck, tags: ["verified", "check"] },
  "badge-dollar-sign": {
    component: LucideBadgeDollarSign,
    tags: [
      "discount",
      "offer",
      "sale",
      "voucher",
      "tag",
      "monetization",
      "marketing",
      "finance",
      "financial",
      "exchange",
      "transaction",
      "payment",
      "usd",
      "$",
    ],
  },
  "badge-euro": {
    component: LucideBadgeEuro,
    tags: [
      "discount",
      "offer",
      "sale",
      "voucher",
      "tag",
      "monetization",
      "marketing",
      "finance",
      "financial",
      "exchange",
      "transaction",
      "payment",
      "€",
    ],
  },
  "badge-help": {
    component: LucideBadgeHelp,
    tags: ["verified", "unverified", "help"],
  },
  "badge-indian-rupee": {
    component: LucideBadgeIndianRupee,
    tags: [
      "discount",
      "offer",
      "sale",
      "voucher",
      "tag",
      "monetization",
      "marketing",
      "finance",
      "financial",
      "exchange",
      "transaction",
      "payment",
      "inr",
      "₹",
    ],
  },
  "badge-info": {
    component: LucideBadgeInfo,
    tags: ["verified", "unverified", "help"],
  },
  "badge-japanese-yen": {
    component: LucideBadgeJapaneseYen,
    tags: [
      "discount",
      "offer",
      "sale",
      "voucher",
      "tag",
      "monetization",
      "marketing",
      "finance",
      "financial",
      "exchange",
      "transaction",
      "payment",
      "jpy",
      "¥",
    ],
  },
  "badge-minus": {
    component: LucideBadgeMinus,
    tags: ["verified", "unverified", "delete", "remove", "erase"],
  },
  "badge-percent": {
    component: LucideBadgePercent,
    tags: [
      "verified",
      "unverified",
      "sale",
      "discount",
      "offer",
      "marketing",
      "sticker",
      "price tag",
    ],
  },
  "badge-plus": {
    component: LucideBadgePlus,
    tags: ["verified", "unverified", "add", "create", "new"],
  },
  "badge-pound-sterling": {
    component: LucideBadgePoundSterling,
    tags: [
      "discount",
      "offer",
      "sale",
      "voucher",
      "tag",
      "monetization",
      "marketing",
      "finance",
      "financial",
      "exchange",
      "transaction",
      "payment",
      "british",
      "gbp",
      "£",
    ],
  },
  "badge-russian-ruble": {
    component: LucideBadgeRussianRuble,
    tags: [
      "discount",
      "offer",
      "sale",
      "voucher",
      "tag",
      "monetization",
      "marketing",
      "finance",
      "financial",
      "exchange",
      "transaction",
      "payment",
      "rub",
      "₽",
    ],
  },
  "badge-swiss-franc": {
    component: LucideBadgeSwissFranc,
    tags: [
      "discount",
      "offer",
      "sale",
      "voucher",
      "tag",
      "monetization",
      "marketing",
      "finance",
      "financial",
      "exchange",
      "transaction",
      "payment",
      "chf",
      "₣",
    ],
  },
  "badge-x": {
    component: LucideBadgeX,
    tags: ["verified", "unverified", "lost", "delete", "remove"],
  },
  badge: { component: LucideBadge, tags: ["check", "verified", "unverified"] },
  ban: {
    component: LucideBan,
    tags: [
      "cancel",
      "no",
      "stop",
      "forbidden",
      "prohibited",
      "error",
      "incorrect",
      "mistake",
      "wrong",
      "failure",
      "circle",
      "slash",
      "null",
      "void",
    ],
  },
  "bar-chart-2": {
    component: LucideBarChart2,
    tags: ["statistics", "diagram", "graph"],
  },
  "bar-chart-3": {
    component: LucideBarChart3,
    tags: ["statistics", "diagram", "graph"],
  },
  "bar-chart-4": {
    component: LucideBarChart4,
    tags: ["statistics", "diagram", "graph"],
  },
  "bar-chart-big": {
    component: LucideBarChartBig,
    tags: ["statistics", "diagram", "graph"],
  },
  "bar-chart-horizontal-big": {
    component: LucideBarChartHorizontalBig,
    tags: ["statistics", "diagram", "graph"],
  },
  "bar-chart-horizontal": {
    component: LucideBarChartHorizontal,
    tags: ["statistics", "diagram", "graph"],
  },
  "bar-chart": {
    component: LucideBarChart,
    tags: ["statistics", "diagram", "graph"],
  },
  baseline: { component: LucideBaseline, tags: ["text", "format", "color"] },
  "bell-dot": {
    component: LucideBellDot,
    tags: ["alarm", "notification", "sound", "reminder", "unread"],
  },
  "bell-off": {
    component: LucideBellOff,
    tags: ["alarm", "notification", "silent", "reminder"],
  },
  "bell-plus": {
    component: LucideBellPlus,
    tags: ["notification", "silent", "reminder", "add", "create", "new"],
  },
  "bell-ring": {
    component: LucideBellRing,
    tags: ["alarm", "notification", "sound", "reminder"],
  },
  bell: {
    component: LucideBell,
    tags: ["alarm", "notification", "sound", "reminder"],
  },
  "between-horizontal-end": {
    component: LucideBetweenHorizontalEnd,
    tags: [
      "insert",
      "add",
      "left",
      "slot",
      "squeeze",
      "space",
      "vertical",
      "grid",
      "table",
      "rows",
      "cells",
      "excel",
      "spreadsheet",
      "accountancy",
      "data",
      "enter",
      "entry",
      "entries",
      "blocks",
      "rectangles",
      "chevron",
    ],
  },
  "between-horizontal-start": {
    component: LucideBetweenHorizontalStart,
    tags: [
      "insert",
      "add",
      "right",
      "slot",
      "squeeze",
      "space",
      "vertical",
      "grid",
      "table",
      "rows",
      "cells",
      "excel",
      "spreadsheet",
      "accountancy",
      "data",
      "enter",
      "entry",
      "entries",
      "blocks",
      "rectangles",
      "chevron",
    ],
  },
  "between-vertical-end": {
    component: LucideBetweenVerticalEnd,
    tags: [
      "insert",
      "add",
      "top",
      "slot",
      "squeeze",
      "space",
      "vertical",
      "grid",
      "table",
      "columns",
      "cells",
      "data",
      "enter",
      "entry",
      "entries",
      "blocks",
      "rectangles",
      "chevron",
    ],
  },
  "between-vertical-start": {
    component: LucideBetweenVerticalStart,
    tags: [
      "insert",
      "add",
      "bottom",
      "slot",
      "squeeze",
      "space",
      "vertical",
      "grid",
      "table",
      "columns",
      "cells",
      "data",
      "enter",
      "entry",
      "entries",
      "blocks",
      "rectangles",
      "chevron",
    ],
  },
  "chevron-down-circle": {
    component: LucideChevronDownCircle,
    tags: ["back", "menu"],
  },
  "chevron-down-square": {
    component: LucideChevronDownSquare,
    tags: ["back", "menu", "panel"],
  },
  "chevron-down": {
    component: LucideChevronDown,
    tags: ["backwards", "reverse", "slow", "dropdown"],
  },
  "chevron-first": {
    component: LucideChevronFirst,
    tags: ["previous", "music"],
  },
  "chevron-last": {
    component: LucideChevronLast,
    tags: ["skip", "next", "music"],
  },
  "chevron-left-circle": {
    component: LucideChevronLeftCircle,
    tags: ["back", "previous", "less than", "fewer", "menu", "<"],
  },
  "chevron-left-square": {
    component: LucideChevronLeftSquare,
    tags: [
      "back",
      "previous",
      "less than",
      "fewer",
      "menu",
      "panel",
      "button",
      "keyboard",
      "<",
    ],
  },
  "chevron-left": {
    component: LucideChevronLeft,
    tags: ["back", "previous", "less than", "fewer", "menu", "<"],
  },
  "chevron-right-circle": {
    component: LucideChevronRightCircle,
    tags: ["back", "more than", "greater", "menu", ">"],
  },
  "chevron-right-square": {
    component: LucideChevronRightSquare,
    tags: [
      "forward",
      "next",
      "more than",
      "greater",
      "menu",
      "panel",
      "code",
      "coding",
      "command line",
      "terminal",
      "prompt",
      "shell",
      "console",
      ">",
    ],
  },
  "chevron-right": {
    component: LucideChevronRight,
    tags: [
      "forward",
      "next",
      "more than",
      "greater",
      "menu",
      "code",
      "coding",
      "command line",
      "terminal",
      "prompt",
      "shell",
      ">",
    ],
  },
  "chevron-up-circle": {
    component: LucideChevronUpCircle,
    tags: ["caret", "ahead", "menu", "^"],
  },
  "chevron-up-square": {
    component: LucideChevronUpSquare,
    tags: [
      "caret",
      "keyboard",
      "button",
      "mac",
      "control",
      "ctrl",
      "superscript",
      "exponential",
      "power",
      "ahead",
      "menu",
      "panel",
      "^",
    ],
  },
  "chevron-up": {
    component: LucideChevronUp,
    tags: [
      "caret",
      "keyboard",
      "mac",
      "control",
      "ctrl",
      "superscript",
      "exponential",
      "power",
      "ahead",
      "fast",
      "^",
      "dropdown",
    ],
  },
  "chevrons-down-up": {
    component: LucideChevronsDownUp,
    tags: ["collapse", "fold", "vertical"],
  },
  "chevrons-down": {
    component: LucideChevronsDown,
    tags: ["backwards", "reverse", "slower"],
  },
  "chevrons-left-right": {
    component: LucideChevronsLeftRight,
    tags: ["expand", "horizontal", "unfold"],
  },
  "chevrons-left": { component: LucideChevronsLeft, tags: ["turn", "corner"] },
  "chevrons-right-left": {
    component: LucideChevronsRightLeft,
    tags: ["collapse", "fold", "horizontal"],
  },
  "chevrons-right": {
    component: LucideChevronsRight,
    tags: ["turn", "corner"],
  },
  "chevrons-up-down": {
    component: LucideChevronsUpDown,
    tags: ["expand", "unfold", "vertical"],
  },
  "chevrons-up": {
    component: LucideChevronsUp,
    tags: ["forward", "ahead", "faster", "speed", "boost"],
  },
  "code-2": {
    component: LucideCode2,
    tags: ["source", "programming", "html", "xml"],
  },
  "code-square": {
    component: LucideCodeSquare,
    tags: ["gist", "source", "programming", "html", "xml", "coding"],
  },
  code: {
    component: LucideCode,
    tags: ["source", "programming", "html", "xml"],
  },
  codepen: { component: LucideCodepen, tags: ["logo"] },
  codesandbox: { component: LucideCodesandbox, tags: ["logo"] },
  cog: {
    component: LucideCog,
    tags: ["computing", "settings", "cog", "edit", "gear", "preferences"],
  },
  "fold-vertical": {
    component: LucideFoldVertical,
    tags: ["arrow", "collapse", "fold", "vertical", "dashed"],
  },
  "folder-open": { component: LucideFolderOpen, tags: ["directory"] },
  "folder-output": {
    component: LucideFolderOutput,
    tags: ["directory", "import", "export"],
  },
  "folder-pen": { component: LucideFolderPen, tags: ["directory", "rename"] },
  "folder-root": {
    component: LucideFolderRoot,
    tags: ["directory", "root", "project", "git", "repo"],
  },
  "folder-search-2": {
    component: LucideFolderSearch2,
    tags: ["directory", "search", "find", "lost", "browser"],
  },
  "folder-search": {
    component: LucideFolderSearch,
    tags: ["directory", "search", "find", "lost", "browser"],
  },
  "folder-symlink": {
    component: LucideFolderSymlink,
    tags: ["directory", "symlink", "symbolic", "link"],
  },
  "folder-sync": {
    component: LucideFolderSync,
    tags: [
      "directory",
      "synchronize",
      "synchronise",
      "refresh",
      "reconnect",
      "transfer",
      "backup",
    ],
  },
  "file-up": { component: LucideFileUp, tags: ["upload", "import", "export"] },
  upload: {
    component: LucideUpload,
    tags: ["directory", "import", "export", "transfer", "backup"],
  },
  "folder-tree": {
    component: LucideFolderTree,
    tags: ["directory", "tree", "browser"],
  },
  "folder-up": {
    component: LucideFolderUp,
    tags: ["directory", "upload", "import", "export"],
  },
  "folder-x": {
    component: LucideFolderX,
    tags: ["directory", "remove", "delete"],
  },
  folder: { component: LucideFolder, tags: ["directory"] },
  folders: {
    component: LucideFolders,
    tags: ["multiple", "copy", "directories"],
  },
  footprints: {
    component: LucideFootprints,
    tags: ["steps", "walking", "foot", "feet", "trail", "shoe"],
  },
  forklift: {
    component: LucideForklift,
    tags: ["vehicle", "transport", "logistics"],
  },
  "form-input": {
    component: LucideFormInput,
    tags: ["2fa", "authenticate", "login", "field", "text"],
  },
  fullscreen: {
    component: LucideFullscreen,
    tags: ["expand", "zoom", "preview", "focus", "camera", "lens", "image"],
  },
  "function-square": {
    component: LucideFunctionSquare,
    tags: ["programming", "code", "automation", "maths"],
  },
  "gallery-horizontal-end": {
    component: LucideGalleryHorizontalEnd,
    tags: [
      "carousel",
      "pictures",
      "images",
      "scroll",
      "swipe",
      "album",
      "portfolio",
      "history",
      "versions",
      "backup",
      "time machine",
    ],
  },
  "gallery-horizontal": {
    component: LucideGalleryHorizontal,
    tags: [
      "carousel",
      "pictures",
      "images",
      "scroll",
      "swipe",
      "album",
      "portfolio",
    ],
  },
  "gallery-thumbnails": {
    component: LucideGalleryThumbnails,
    tags: ["carousel", "pictures", "images", "album", "portfolio", "preview"],
  },
  "gallery-vertical-end": {
    component: LucideGalleryVerticalEnd,
    tags: [
      "carousel",
      "pictures",
      "images",
      "scroll",
      "swipe",
      "album",
      "portfolio",
      "history",
      "versions",
      "backup",
      "time machine",
    ],
  },
  "gallery-vertical": {
    component: LucideGalleryVertical,
    tags: [
      "carousel",
      "pictures",
      "images",
      "scroll",
      "swipe",
      "album",
      "portfolio",
    ],
  },
  "gantt-chart-square": {
    component: LucideGanttChartSquare,
    tags: [
      "projects",
      "manage",
      "overview",
      "roadmap",
      "plan",
      "intentions",
      "timeline",
      "deadline",
      "date",
      "event",
      "range",
      "period",
      "productivity",
      "work",
      "agile",
      "code",
      "coding",
      "toolbar",
      "button",
    ],
  },
  "gantt-chart": {
    component: LucideGanttChart,
    tags: [
      "projects",
      "manage",
      "overview",
      "roadmap",
      "plan",
      "intentions",
      "timeline",
      "deadline",
      "date",
      "event",
      "range",
      "period",
      "productivity",
      "work",
      "agile",
      "code",
      "coding",
    ],
  },
  "git-branch-plus": {
    component: LucideGitBranchPlus,
    tags: ["add", "create", "+"],
  },
  "git-branch": {
    component: LucideGitBranch,
    tags: ["code", "version control"],
  },
  "git-commit-horizontal": {
    component: LucideGitCommitHorizontal,
    tags: ["code", "version control", "waypoint", "stop", "station"],
  },
  "git-commit-vertical": {
    component: LucideGitCommitVertical,
    tags: ["code", "version control", "waypoint", "stop", "station"],
  },
  "git-compare-arrows": {
    component: LucideGitCompareArrows,
    tags: ["code", "version control", "diff"],
  },
  "git-compare": {
    component: LucideGitCompare,
    tags: ["code", "version control", "diff"],
  },
  "git-fork": { component: LucideGitFork, tags: ["code", "version control"] },
  "git-graph": {
    component: LucideGitGraph,
    tags: ["code", "version control", "commit graph", "commits", "gitlens"],
  },
  "git-merge": { component: LucideGitMerge, tags: ["code", "version control"] },
  "git-pull-request-arrow": {
    component: LucideGitPullRequestArrow,
    tags: ["code", "version control", "open"],
  },
  "git-pull-request-closed": {
    component: LucideGitPullRequestClosed,
    tags: ["code", "version control", "rejected", "closed", "cancelled", "x"],
  },
  "git-pull-request-create-arrow": {
    component: LucideGitPullRequestCreateArrow,
    tags: ["code", "version control", "open", "plus", "add", "+"],
  },
  "git-pull-request-create": {
    component: LucideGitPullRequestCreate,
    tags: ["code", "version control", "open", "plus", "add", "+"],
  },
  "git-pull-request-draft": {
    component: LucideGitPullRequestDraft,
    tags: ["code", "version control", "open", "draft", "dashed"],
  },
  "git-pull-request": {
    component: LucideGitPullRequest,
    tags: ["code", "version control", "open"],
  },
  github: { component: LucideGithub, tags: ["logo", "version control"] },
  gitlab: { component: LucideGitlab, tags: ["logo", "version control"] },
  "globe-2": {
    component: LucideGlobe2,
    tags: ["world", "browser", "language", "translate"],
  },
  globe: {
    component: LucideGlobe,
    tags: ["world", "browser", "language", "translate"],
  },
  "heading-1": {
    component: LucideHeading1,
    tags: ["h1", "html", "markup", "markdown"],
  },
  "heading-2": {
    component: LucideHeading2,
    tags: ["h2", "html", "markup", "markdown"],
  },
  "heading-3": {
    component: LucideHeading3,
    tags: ["h3", "html", "markup", "markdown"],
  },
  "heading-4": {
    component: LucideHeading4,
    tags: ["h4", "html", "markup", "markdown"],
  },
  "heading-5": {
    component: LucideHeading5,
    tags: ["h5", "html", "markup", "markdown"],
  },
  "heading-6": {
    component: LucideHeading6,
    tags: ["h6", "html", "markup", "markdown"],
  },
  heading: {
    component: LucideHeading,
    tags: ["h1", "html", "markup", "markdown"],
  },
  highlighter: { component: LucideHighlighter, tags: ["mark", "text"] },
  history: {
    component: LucideHistory,
    tags: [
      "time",
      "redo",
      "undo",
      "rewind",
      "timeline",
      "version",
      "time machine",
      "backup",
      "rotate",
      "ccw",
    ],
  },
  "image-down": { component: LucideImageDown, tags: ["picture", "photo"] },
  "image-minus": { component: LucideImageMinus, tags: ["remove", "delete"] },
  "image-off": { component: LucideImageOff, tags: ["picture", "photo"] },
  "image-plus": { component: LucideImagePlus, tags: ["add", "create"] },
  image: { component: LucideImage, tags: ["picture", "photo"] },

  import: { component: LucideImport, tags: ["save"] },
  inbox: { component: LucideInbox, tags: ["email"] },
  info: { component: LucideInfo, tags: ["help"] },
  instagram: { component: LucideInstagram, tags: ["logo", "camera", "social"] },
  italic: { component: LucideItalic, tags: ["oblique", "text", "format"] },
  "kanban-square": {
    component: LucideKanbanSquare,
    tags: [
      "projects",
      "manage",
      "overview",
      "board",
      "tickets",
      "issues",
      "roadmap",
      "plan",
      "intentions",
      "productivity",
      "work",
      "agile",
      "code",
      "coding",
      "toolbar",
      "button",
    ],
  },
  key: {
    component: LucideKey,
    tags: [
      "password",
      "login",
      "authentication",
      "secure",
      "unlock",
      "keychain",
      "key ring",
      "fob",
    ],
  },
  keyboard: {
    component: LucideKeyboard,
    tags: ["layout", "spell", "settings", "mouse"],
  },
  "line-chart": {
    component: LucideLineChart,
    tags: ["statistics", "diagram", "graph"],
  },
  "link-2-off": { component: LucideLink2Off, tags: ["unchain", "chain"] },
  "link-2": { component: LucideLink2, tags: ["chain", "url"] },
  link: { component: LucideLink, tags: ["chain", "url"] },
  linkedin: {
    component: LucideLinkedin,
    tags: ["logo", "social media", "social"],
  },
  "list-checks": {
    component: LucideListChecks,
    tags: [
      "todo",
      "done",
      "check",
      "tick",
      "complete",
      "tasks",
      "items",
      "pending",
    ],
  },
  "list-collapse": {
    component: LucideListCollapse,
    tags: [
      "items",
      "collapse",
      "expand",
      "details",
      "disclosure",
      "show",
      "hide",
      "toggle",
      "accordion",
      "more",
      "less",
      "fold",
      "unfold",
    ],
  },
  "list-end": {
    component: LucideListEnd,
    tags: ["queue", "bottom", "end", "playlist"],
  },
  "list-filter": { component: LucideListFilter, tags: ["options"] },
  "list-minus": {
    component: LucideListMinus,
    tags: ["playlist", "remove", "song", "subtract", "delete", "unqueue"],
  },
  "list-music": {
    component: LucideListMusic,
    tags: ["playlist", "queue", "music", "audio", "playback"],
  },
  "list-ordered": {
    component: LucideListOrdered,
    tags: ["number", "order", "queue"],
  },
  "list-plus": {
    component: LucideListPlus,
    tags: ["playlist", "add", "song", "track", "new"],
  },
  "list-restart": {
    component: LucideListRestart,
    tags: ["reset", "refresh", "reload", "playlist", "replay"],
  },
  "list-start": {
    component: LucideListStart,
    tags: ["queue", "top", "start", "next", "playlist"],
  },
  "list-todo": {
    component: LucideListTodo,
    tags: [
      "todo",
      "done",
      "check",
      "tick",
      "complete",
      "tasks",
      "items",
      "pending",
    ],
  },
  "list-tree": { component: LucideListTree, tags: ["tree", "browser"] },
  "list-video": {
    component: LucideListVideo,
    tags: ["playlist", "video", "playback"],
  },
  "list-x": {
    component: LucideListX,
    tags: ["playlist", "subtract", "remove", "delete", "unqueue"],
  },
  "loader-2": { component: LucideLoader2, tags: ["load"] },
  loader: { component: LucideLoader, tags: ["load", "wait"] },
  "log-in": {
    component: LucideLogIn,
    tags: ["sign in", "arrow", "enter", "auth"],
  },
  "log-out": {
    component: LucideLogOut,
    tags: ["sign out", "arrow", "exit", "auth"],
  },
  mailbox: {
    component: LucideMailbox,
    tags: ["emails", "messages", "letters", "mailing list", "newsletter"],
  },
  "maximize-2": {
    component: LucideMaximize2,
    tags: ["fullscreen", "arrows", "expand"],
  },
  maximize: {
    component: LucideMaximize,
    tags: ["fullscreen", "expand", "dashed"],
  },
  "menu-square": {
    component: LucideMenuSquare,
    tags: ["bars", "navigation", "hamburger", "options", "menu bar", "panel"],
  },
  menu: {
    component: LucideMenu,
    tags: ["bars", "navigation", "hamburger", "options"],
  },
  merge: { component: LucideMerge, tags: ["combine", "join", "unite"] },
  "move-3d": {
    component: LucideMove3d,
    tags: ["arrows", "axis", "gizmo", "coordinates", "transform", "translate"],
  },
  "move-diagonal-2": {
    component: LucideMoveDiagonal2,
    tags: ["double", "arrow"],
  },
  "move-diagonal": { component: LucideMoveDiagonal, tags: ["double", "arrow"] },
  "move-down-left": {
    component: LucideMoveDownLeft,
    tags: ["arrow", "direction"],
  },
  "move-down-right": {
    component: LucideMoveDownRight,
    tags: ["arrow", "direction"],
  },
  "move-down": {
    component: LucideMoveDown,
    tags: ["arrow", "direction", "downwards", "south"],
  },
  "move-horizontal": {
    component: LucideMoveHorizontal,
    tags: ["double", "arrow"],
  },
  "move-left": {
    component: LucideMoveLeft,
    tags: ["arrow", "direction", "back", "west"],
  },
  "move-right": {
    component: LucideMoveRight,
    tags: ["arrow", "direction", "trend flat", "east"],
  },
  "move-up-left": { component: LucideMoveUpLeft, tags: ["arrow", "direction"] },
  "move-up-right": {
    component: LucideMoveUpRight,
    tags: ["arrow", "direction"],
  },
  "move-up": {
    component: LucideMoveUp,
    tags: ["arrow", "direction", "upwards", "north"],
  },
  "move-vertical": { component: LucideMoveVertical, tags: ["double", "arrow"] },
  move: { component: LucideMove, tags: ["arrows"] },
  navigation: { component: LucideNavigation, tags: ["location", "travel"] },
  network: { component: LucideNetwork, tags: ["tree"] },
  "panel-bottom-close": {
    component: LucidePanelBottomClose,
    tags: ["drawer", "dock", "hide", "chevron", "down"],
  },
  "panel-bottom-open": {
    component: LucidePanelBottomOpen,
    tags: ["drawer", "dock", "show", "reveal", "chevron", "up"],
  },
  "panel-left-close": {
    component: LucidePanelLeftClose,
    tags: ["primary", "drawer", "hide", "chevron", "<"],
  },
  "panel-left-open": {
    component: LucidePanelLeftOpen,
    tags: ["primary", "drawer", "show", "reveal", "chevron", "right", ">"],
  },
  "panel-right-close": {
    component: LucidePanelRightClose,
    tags: ["sidebar", "secondary", "drawer", "hide", "chevron", ">"],
  },
  "panel-right-open": {
    component: LucidePanelRightOpen,
    tags: [
      "sidebar",
      "secondary",
      "drawer",
      "show",
      "reveal",
      "chevron",
      "left",
      "<",
    ],
  },
  "panel-top-close": {
    component: LucidePanelTopClose,
    tags: ["menu bar", "drawer", "hide", "chevron", "up"],
  },
  "panel-top-open": {
    component: LucidePanelTopOpen,
    tags: ["menu bar", "drawer", "show", "reveal", "chevron", "down"],
  },
  pause: { component: LucidePause, tags: ["music", "stop"] },
  phone: { component: LucidePhone, tags: ["call"] },
  "pi-square": {
    component: LucidePiSquare,
    tags: [
      "constant",
      "code",
      "coding",
      "programming",
      "symbol",
      "trigonometry",
      "geometry",
      "formula",
    ],
  },
  pi: {
    component: LucidePi,
    tags: [
      "constant",
      "code",
      "coding",
      "programming",
      "symbol",
      "trigonometry",
      "geometry",
      "formula",
    ],
  },
  "plus-circle": {
    component: LucidePlusCircle,
    tags: [
      "add",
      "new",
      "increase",
      "increment",
      "positive",
      "calculate",
      "crosshair",
      "aim",
      "target",
      "scope",
      "sight",
      "reticule",
      "maximum",
      "upgrade",
      "extra",
      "operator",
      "join",
      "concatenate",
      "code",
      "coding",
      "+",
    ],
  },
  "plus-square": {
    component: LucidePlusSquare,
    tags: [
      "add",
      "new",
      "increase",
      "increment",
      "positive",
      "calculate",
      "calculator",
      "button",
      "keyboard",
      "toolbar",
      "maximum",
      "upgrade",
      "extra",
      "operator",
      "join",
      "concatenate",
      "code",
      "coding",
      "+",
    ],
  },
  plus: {
    component: LucidePlus,
    tags: [
      "add",
      "new",
      "increase",
      "increment",
      "positive",
      "calculate",
      "toolbar",
      "crosshair",
      "aim",
      "target",
      "scope",
      "sight",
      "reticule",
      "maximum",
      "upgrade",
      "extra",
      "+",
    ],
  },
  "pointer-off": { component: LucidePointerOff, tags: ["mouse"] },
  pointer: { component: LucidePointer, tags: ["mouse"] },
  "qr-code": {
    component: LucideQrCode,
    tags: ["barcode", "scan", "link", "url", "information", "digital"],
  },
  router: { component: LucideRouter, tags: ["computer", "server", "cloud"] },
  "rows-2": {
    component: LucideRows2,
    tags: [
      "lines",
      "list",
      "queue",
      "preview",
      "panel",
      "paragraphs",
      "parallel",
      "series",
      "split",
      "vertical",
      "horizontal",
      "half",
      "center",
      "middle",
      "even",
      "drawer",
    ],
  },
  "rows-3": {
    component: LucideRows3,
    tags: [
      "lines",
      "list",
      "queue",
      "preview",
      "paragraphs",
      "parallel",
      "series",
      "split",
      "vertical",
      "horizontal",
      "half",
      "center",
      "middle",
      "even",
      "drawers",
    ],
  },
  "rows-4": {
    component: LucideRows4,
    tags: [
      "lines",
      "list",
      "queue",
      "preview",
      "paragraphs",
      "parallel",
      "series",
      "split",
      "vertical",
      "horizontal",
      "half",
      "center",
      "middle",
      "even",
      "drawers",
      "grill",
    ],
  },
  "save-all": { component: LucideSaveAll, tags: ["floppy disks", "copy"] },
  save: { component: LucideSave, tags: ["floppy disk"] },
  "scale-3d": {
    component: LucideScale3d,
    tags: ["gizmo", "transform", "size"],
  },
  scale: {
    component: LucideScale,
    tags: ["balance", "legal", "license", "right", "rule", "law"],
  },
  scaling: { component: LucideScaling, tags: ["scale", "resize", "design"] },
  "screen-share-off": {
    component: LucideScreenShareOff,
    tags: ["desktop", "disconnect", "monitor"],
  },
  "screen-share": {
    component: LucideScreenShare,
    tags: ["host", "desktop", "monitor"],
  },
  "scroll-text": {
    component: LucideScrollText,
    tags: [
      "paper",
      "log",
      "scripture",
      "document",
      "notes",
      "parchment",
      "list",
      "long",
      "script",
      "story",
      "code",
      "coding",
    ],
  },
  scroll: {
    component: LucideScroll,
    tags: [
      "paper",
      "log",
      "scripture",
      "document",
      "notes",
      "parchment",
      "list",
      "long",
      "script",
      "story",
      "code",
      "coding",
    ],
  },
  "search-check": {
    component: LucideSearchCheck,
    tags: [
      "find",
      "scan",
      "magnifier",
      "magnifying glass",
      "found",
      "correct",
      "complete",
      "tick",
    ],
  },
  "search-code": {
    component: LucideSearchCode,
    tags: [
      "find",
      "scan",
      "magnifier",
      "magnifying glass",
      "grep",
      "chevrons",
      "<>",
    ],
  },
  x: {
    component: LucideX,
    tags: [
      "close",
      "remove",
      "delete",
      "cancel",
      "abort",
      "exit",
      "x",
      "cross",
      "times",
      "multiply",
      "clear",
      "stop",
    ],
  },
  "search-slash": {
    component: LucideSearchSlash,
    tags: [
      "find",
      "scan",
      "magnifier",
      "magnifying glass",
      "stop",
      "clear",
      "cancel",
      "abort",
      "/",
    ],
  },
  "search-x": {
    component: LucideSearchX,
    tags: [
      "find",
      "scan",
      "magnifier",
      "magnifying glass",
      "stop",
      "clear",
      "cancel",
      "abort",
    ],
  },
  search: {
    component: LucideSearch,
    tags: ["find", "scan", "magnifier", "magnifying glass"],
  },
  "send-to-back": {
    component: LucideSendToBack,
    tags: [
      "bring",
      "send",
      "move",
      "under",
      "back",
      "backwards",
      "overlap",
      "layer",
      "order",
    ],
  },
  send: {
    component: LucideSend,
    tags: [
      "email",
      "message",
      "mail",
      "paper airplane",
      "paper aeroplane",
      "submit",
    ],
  },
  "separator-horizontal": {
    component: LucideSeparatorHorizontal,
    tags: ["move", "split"],
  },
  "separator-vertical": {
    component: LucideSeparatorVertical,
    tags: ["move", "split"],
  },
  "skip-back": {
    component: LucideSkipBack,
    tags: ["arrow", "previous", "music"],
  },
  "skip-forward": {
    component: LucideSkipForward,
    tags: ["arrow", "skip", "next", "music"],
  },
  skull: { component: LucideSkull, tags: ["death", "danger", "bone"] },
  slack: { component: LucideSlack, tags: ["logo"] },
  "slash-square": {
    component: LucideSlashSquare,
    tags: [
      "git",
      "diff",
      "ignored",
      "divide",
      "division",
      "shortcut",
      "or",
      "/",
    ],
  },
  slash: { component: LucideSlash, tags: ["divide", "division", "or", "/"] },
  slice: { component: LucideSlice, tags: ["cutter", "scalpel", "knife"] },
  "step-back": {
    component: LucideStepBack,
    tags: ["arrow", "previous", "music", "left", "reverse"],
  },
  "step-forward": {
    component: LucideStepForward,
    tags: ["arrow", "next", "music", "right", "continue"],
  },
  strikethrough: {
    component: LucideStrikethrough,
    tags: ["cross out", "delete", "remove", "format"],
  },
  "text-cursor-input": { component: LucideTextCursorInput, tags: ["select"] },
  "text-cursor": { component: LucideTextCursor, tags: ["select"] },
  "text-quote": {
    component: LucideTextQuote,
    tags: ["blockquote", "quotation", "indent", "reply", "response"],
  },
  "text-search": {
    component: LucideTextSearch,
    tags: [
      "find",
      "data",
      "copy",
      "txt",
      "pdf",
      "document",
      "scan",
      "magnifier",
      "magnifying glass",
    ],
  },
  "text-select": {
    component: LucideTextSelect,
    tags: ["find", "search", "selection", "dashed"],
  },
  text: {
    component: LucideText,
    tags: ["find", "search", "data", "txt", "pdf", "document"],
  },
  "triangle-right": {
    component: LucideTriangleRight,
    tags: [
      "volume",
      "controls",
      "controller",
      "tv remote",
      "geometry",
      "delta",
      "ramp",
      "slope",
      "incline",
      "increase",
    ],
  },
  type: { component: LucideType, tags: ["text", "format", "markdown"] },
  bold: { component: LucideBold, tags: ["text", "format", "markdown"] },
  triangle: {
    component: LucideTriangle,
    tags: ["equilateral", "delta", "shape", "pyramid", "hierarchy"],
  },
  underline: { component: LucideUnderline, tags: ["text", "format"] },
  "undo-2": {
    component: LucideUndo2,
    tags: [
      "redo",
      "rerun",
      "history",
      "back",
      "return",
      "reverse",
      "revert",
      "direction",
      "u-turn",
    ],
  },
  "undo-dot": {
    component: LucideUndoDot,
    tags: ["redo", "history", "step", "back"],
  },
  undo: { component: LucideUndo, tags: ["redo", "rerun", "history"] },
  "unfold-horizontal": {
    component: LucideUnfoldHorizontal,
    tags: ["arrow", "collapse", "fold", "vertical", "dashed"],
  },
  "unfold-vertical": {
    component: LucideUnfoldVertical,
    tags: ["arrow", "expand", "vertical", "dashed"],
  },
  ungroup: {
    component: LucideUngroup,
    tags: [
      "cubes",
      "packages",
      "parts",
      "units",
      "collection",
      "cluster",
      "separate",
    ],
  },
  "unlink-2": { component: LucideUnlink2, tags: ["url", "unchain"] },
  unlink: { component: LucideUnlink, tags: ["url", "unchain"] },
  unlock: { component: LucideUnlock, tags: ["security"] },
  "user-check": {
    component: LucideUserCheck,
    tags: [
      "followed",
      "subscribed",
      "done",
      "todo",
      "tick",
      "complete",
      "task",
    ],
  },
  "user-cog": {
    component: LucideUserCog,
    tags: ["settings", "edit", "cog", "gear"],
  },
  "user-minus": {
    component: LucideUserMinus,
    tags: ["delete", "remove", "unfollow", "unsubscribe"],
  },
  "user-plus": {
    component: LucideUserPlus,
    tags: ["new", "add", "create", "follow", "subscribe"],
  },
  "user-round-check": {
    component: LucideUserRoundCheck,
    tags: [
      "followed",
      "subscribed",
      "done",
      "todo",
      "tick",
      "complete",
      "task",
    ],
  },
  "user-round-cog": {
    component: LucideUserRoundCog,
    tags: ["settings", "edit", "cog", "gear"],
  },
  "user-round-minus": {
    component: LucideUserRoundMinus,
    tags: ["delete", "remove", "unfollow", "unsubscribe"],
  },
  "user-round-plus": {
    component: LucideUserRoundPlus,
    tags: ["new", "add", "create", "follow", "subscribe"],
  },
  "user-round-search": {
    component: LucideUserRoundSearch,
    tags: [
      "person",
      "account",
      "contact",
      "find",
      "scan",
      "magnifier",
      "magnifying glass",
    ],
  },
  "user-round-x": {
    component: LucideUserRoundX,
    tags: ["delete", "remove", "unfollow", "unsubscribe", "unavailable"],
  },
  "user-round": {
    component: LucideUserRound,
    tags: ["person", "account", "contact"],
  },
  "user-search": {
    component: LucideUserSearch,
    tags: [
      "person",
      "account",
      "contact",
      "find",
      "scan",
      "magnifier",
      "magnifying glass",
    ],
  },
  "user-x": {
    component: LucideUserX,
    tags: ["delete", "remove", "unfollow", "unsubscribe", "unavailable"],
  },
  user: { component: LucideUser, tags: ["person", "account", "contact"] },
  "users-round": { component: LucideUsersRound, tags: ["group", "people"] },
  users: { component: LucideUsers, tags: ["group", "people"] },
  vote: {
    component: LucideVote,
    tags: ["vote", "poll", "ballot", "political", "social", "check", "tick"],
  },

  webhook: {
    component: LucideWebhook,
    tags: ["push api", "interface", "callback"],
  },
  "zoom-in": { component: LucideZoomIn, tags: ["magnifying glass", "plus"] },
  "zoom-out": { component: LucideZoomOut, tags: ["magnifying glass", "plus"] },

  // Add more icons as needed
} as const;

export type LucideIconNames = keyof typeof lucideIconMap;

export default lucideIconMap;
